#!/usr/bin/env bash
has_content() { true; }
log() { true; }

<h1>Wapiti Improvised — Scan Report</h1>

<div class="meta">
  <strong>Target:</strong> ${DOMAIN:-Bulk Scan}<br>
  <strong>Date:</strong> $(date)<br>
  <strong>Mode:</strong> $MODE<br>
  <strong>Duration:</strong> ${duration_min} minutes<br>
  <strong>Output:</strong> $OUTDIR
</div>

<h2>Executive Summary</h2>

<div class="grid">
  <div class="stat-box"><div class="num">$st_subs</div><div class="label">Subdomains</div></div>
  <div class="stat-box"><div class="num">$st_live</div><div class="label">Live Hosts</div></div>
  <div class="stat-box"><div class="num">$st_ips</div><div class="label">IPs</div></div>
  <div class="stat-box"><div class="num">$st_ports</div><div class="label">Open Ports</div></div>
  <div class="stat-box"><div class="num">$st_urls</div><div class="label">URLs</div></div>
  <div class="stat-box"><div class="num">$st_js</div><div class="label">JS Files</div></div>
</div>

<h2>Vulnerability Summary</h2>

<div class="grid">
  <div class="stat-box"><div class="num ${n_critical:+critical}">$n_critical</div><div class="label">Critical</div></div>
  <div class="stat-box"><div class="num ${n_high:+high}">$n_high</div><div class="label">High</div></div>
  <div class="stat-box"><div class="num">$n_medium</div><div class="label">Medium</div></div>
  <div class="stat-box"><div class="num">$n_low</div><div class="label">Low</div></div>
</div>

<table>
<tr><th>Category</th><th>Count</th></tr>
<tr><td>Nuclei Total</td><td><strong>$st_nuclei</strong></td></tr>
<tr><td>Wapiti Findings</td><td>$st_wapiti</td></tr>
<tr><td>Secrets in JS</td><td class="${st_secrets:+critical}">$st_secrets</td></tr>
<tr><td>Fuzzing Results</td><td>$st_fuzz</td></tr>
<tr><td>CORS Misconfigs</td><td class="${st_cors:+high}">$st_cors</td></tr>
<tr><td>Parameterized URLs</td><td>$st_params</td></tr>
</table>

HTMLEOF

    # Add secrets warning
    if [[ $st_secrets -gt 0 ]]; then
        cat >> "$HTML_REPORT" << 'SECEOF'
<div class="warn">
  <strong>⚠ SECRETS FOUND!</strong> Hardcoded credentials, API keys, or tokens were discovered.
  These should be rotated immediately.
</div>
SECEOF
    fi

    # Add findings sections
    if has_content "$OUTDIR/nuclei/nuclei_cve_critical.txt"; then
        echo -e "\n<h2>Critical & High CVEs</h2>\n<pre>" >> "$HTML_REPORT"
        cat "$OUTDIR/nuclei/nuclei_cve_critical.txt" >> "$HTML_REPORT"
        echo "</pre>" >> "$HTML_REPORT"
    fi

    if has_content "$OUTDIR/js/secrets_found.txt"; then
        echo -e "\n<h2>Secrets Found</h2>\n<pre>" >> "$HTML_REPORT"
        cat "$OUTDIR/js/secrets_found.txt" >> "$HTML_REPORT"
        echo "</pre>" >> "$HTML_REPORT"
    fi

    if has_content "$OUTDIR/nuclei/nuclei_takeover.txt"; then
        echo -e "\n<h2>Subdomain Takeover</h2>\n<pre>" >> "$HTML_REPORT"
        cat "$OUTDIR/nuclei/nuclei_takeover.txt" >> "$HTML_REPORT"
        echo "</pre>" >> "$HTML_REPORT"
    fi

    if has_content "$OUTDIR/nuclei/cors_vuln.txt"; then
        echo -e "\n<h2>CORS Misconfigurations</h2>\n<pre>" >> "$HTML_REPORT"
        cat "$OUTDIR/nuclei/cors_vuln.txt" >> "$HTML_REPORT"
        echo "</pre>" >> "$HTML_REPORT"
    fi

    # Tech stack
    if has_content "$OUTDIR/live/tech_summary.txt"; then
        echo -e "\n<h2>Technology Stack</h2>\n<pre>" >> "$HTML_REPORT"
        cat "$OUTDIR/live/tech_summary.txt" >> "$HTML_REPORT"
        echo "</pre>" >> "$HTML_REPORT"
    fi

    # Footer & close
    cat >> "$HTML_REPORT" << 'HTMLEOF'

<h2>Recommendations</h2>

<ol>
  <li><strong>Rotate exposed credentials</strong> immediately — any API keys, tokens, or passwords found in JavaScript files are publicly accessible</li>
  <li><strong>Patch critical and high severity CVEs</strong> identified by the Nuclei vulnerability scanner</li>
  <li><strong>Fix CORS misconfigurations</strong> — only allow specific trusted origins with proper origin validation</li>
  <li><strong>Secure subdomain takeovers</strong> — claim or remove dangling CNAME records pointing to unclaimed cloud services</li>
  <li><strong>Remove sensitive files</strong> from public web roots, including .env, .git directories, backup files, and configuration files</li>
  <li><strong>Implement proper authentication</strong> on any discovered admin panels, dashboards, and internal tools</li>
  <li><strong>Add rate limiting</strong> on authentication and API endpoints to prevent brute force and abuse</li>
  <li><strong>Review and remediate Wapiti findings</strong> in severity order (Critical → High → Medium → Low)</li>
  <li><strong>Implement security headers</strong> — Content-Security-Policy, Strict-Transport-Security, X-Frame-Options</li>
  <li><strong>Set up recurring scans</strong> — schedule automated weekly scans to catch new vulnerabilities</li>
</ol>

<div class="footer">
  Generated by Wapiti Improvised v3.0 — The Ultimate All-in-One Web Security Scanner<br>
  <em>For authorized security testing only</em>
</div>

</body>
</html>
HTMLEOF

    log "HTML report: $HTML_REPORT"
    log "Markdown report: $REPORT"

    # ---- Generate JSON Report ----
    log "Generating JSON report ..."
    local JSON_REPORT="$OUTDIR/reports/full_scan_report.json"
    {
        # Build findings array
        local json_findings="[]"
        local first=true

        # Add nuclei critical/high findings
        if has_content "$OUTDIR/nuclei/nuclei_cve_critical.txt"; then
            while IFS= read -r line; do
                if $first; then json_findings="["; first=false; else json_findings="${json_findings},"; fi
                local escaped=$(echo "$line" | sed 's/"/\\"/g')
                json_findings="${json_findings}{\"type\":\"nuclei_cve\",\"severity\":\"critical\",\"detail\":\"${escaped}\"}"
            done < "$OUTDIR/nuclei/nuclei_cve_critical.txt"
        fi

        # Add secrets
        if has_content "$OUTDIR/js/secrets_found.txt"; then
            head -20 "$OUTDIR/js/secrets_found.txt" | while IFS= read -r line; do
                escaped=$(echo "$line" | sed 's/"/\\"/g')
                jq -n --arg t "secret" --arg s "high" --arg d "$escaped" \
                    '{type: $t, severity: $s, detail: $d}' 2>/dev/null || true
            done
        fi

        # Write JSON
        cat > "$JSON_REPORT" << JSONEOF
{
  "scan_metadata": {
    "tool": "Wapiti Improvised v3.0",
    "target": "${DOMAIN:-bulk}",
    "date": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
    "mode": "$MODE",
    "duration_minutes": ${duration_min}
  },
  "statistics": {
    "subdomains": ${st_subs},
    "live_hosts": ${st_live},
    "ips": ${st_ips},
    "open_ports": ${st_ports},
    "urls_collected": ${st_urls},
    "js_files": ${st_js},
    "parameterized_urls": ${st_params}
  },
  "vulnerabilities": {
    "nuclei_total": ${st_nuclei},
    "critical": ${n_critical},
    "high": ${n_high},
    "medium": ${n_medium},
    "low": ${n_low},
    "info": ${n_info},
    "secrets": ${st_secrets},
    "cors_misconfigs": ${st_cors},
    "fuzz_interesting": ${st_fuzz}
  },
  "report_files": {
    "markdown": "$REPORT",
    "html": "$HTML_REPORT",
    "json": "$JSON_REPORT",
    "output_dir": "$OUTDIR"
  }
}
JSONEOF
    } 2>/dev/null || echo "{\"error\":\"JSON generation failed\"}" > "$JSON_REPORT"
    log "JSON report: $JSON_REPORT"

    # ---- Generate CSV Report ----
    log "Generating CSV report ..."
    local CSV_REPORT="$OUTDIR/reports/full_scan_report.csv"
    {
        echo "Category,Count,Details"
        echo "Subdomains,${st_subs},Total unique subdomains discovered"
        echo "Live Hosts,${st_live},Responding HTTP/HTTPS hosts"
        echo "Unique IPs,${st_ips},Total unique IP addresses"
        echo "Open Ports,${st_ports},All open TCP ports found"
        echo "URLs Collected,${st_urls},Total unique URLs"
        echo "JS Files,${st_js},JavaScript files discovered"
        echo "Parameterized URLs,${st_params},URLs containing query parameters"
        echo "Nuclei Total,${st_nuclei},All Nuclei findings combined"
        echo "Critical CVEs,${n_critical},Critical and High severity CVEs"
        echo "Secrets Found,${st_secrets},Hardcoded credentials in JS"
        echo "CORS Misconfigs,${st_cors},Reflective/wildcard CORS issues"
        echo "Fuzzing Interesting,${st_fuzz},HTTP 200/401/403 fuzz results"

        # Add nuclei findings as rows
        if has_content "$OUTDIR/nuclei/nuclei_cve_critical.txt"; then
            while IFS= read -r line; do
                local escaped=$(echo "$line" | sed 's/"/""/g')
                echo "Critical CVE,,${escaped}"
            done < "$OUTDIR/nuclei/nuclei_cve_critical.txt"
        fi
        if has_content "$OUTDIR/nuclei/cors_vuln.txt"; then
            while IFS= read -r line; do
                local escaped=$(echo "$line" | sed 's/"/""/g')
                echo "CORS Issue,,${escaped}"
            done < "$OUTDIR/nuclei/cors_vuln.txt"
        fi
    } > "$CSV_REPORT" 2>/dev/null || true
    log "CSV report: $CSV_REPORT"

    log "Report generation complete."

    # ---- Save scan state for diffing ----
    save_diff_state

    # ---- Send final notification ----
    local total_findings=$(( st_nuclei + st_secrets + st_fuzz + st_cors ))
    if [[ $total_findings -gt 0 ]]; then
        send_notification "Scan COMPLETE for ${DOMAIN:-bulk}. ${total_findings} total findings. Report: ${OUTDIR}/reports/full_scan_report.html" "critical"
    else
        send_notification "Scan complete for ${DOMAIN:-bulk}. No findings detected." "info"
    fi

    local elapsed=$(timer_end)
    log "Phase 9 complete in ${elapsed}"
}# ============================================================================# PART 19: MAIN EXECUTION ENGINE
# ============================================================================

}
true
